version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    image: eslogstash:latest
    ports:
      - 5000:5000
      - 5001:5001
      - 5002:5002
      - 5010:5010
      - 9600:9600
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: bash -c "./wait-for-it.sh -t 360 elasticsearch:9200  -- ./insert-logstash-template.sh && /usr/local/bin/docker-entrypoint -f /usr/share/logstash/pipeline/ --http.host 0.0.0.0 --http.port 9600"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
