#
# Name of this configuration group.
#
spring-security-module:
  #
  # Low priority, allowing other configurations to override
  #
  priority: 1
  #
  # List of interfaces, classes, annotations that should always be exposed.
  #
  exposed:
    - org.springframework.security.config.annotation.web.WebSecurityConfigurer
  #
  # Auto-configuration class rules.
  #
  auto-configuration:
    org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration: false
    org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration: false
    org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration:
      destination: SpringSecurityModule